name: My Nerd Story
description: Women in tech tell their origin stories.
url: http://mynerdstory.org
baseurl: /

markdown: rdiscount

permalink: /:year/:month/:day/:title
lsi: false

exclude:
- CNAME
- README.md
- /scss/